// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/mission-command-intro.scene.json";
import recipe1 from "./scenes/investigation-evidence-reveal.scene.json";
export const sceneModules = {
  "src/flute/scenes/mission-command-intro.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/mission-command-intro.jsx": () => import("./scenes/mission-command-intro"),
  "src/flute/scenes/investigation-evidence-reveal.scene.json": async () => ({default:recipe1}),
  "src/flute/scenes/investigation-evidence-reveal.jsx": () => import("./scenes/investigation-evidence-reveal"),
};
