"""Teaches Alembic our async engine, our metadata, and which objects it is not allowed to manage.

what  : The Alembic environment. Reads the DSN from `app.config`, imports `Base.metadata` from
        `app.db.models`, and runs migrations through the same asyncpg driver the application uses.
where : Executed by every `uv run alembic ...` command. Nothing in `app/` imports it.
how   : Three decisions here, each of which is a bug the first time it is skipped.

        **The URL comes from `app.config`, never from `alembic.ini`.** A second place to configure the
        database is a second place to point at the wrong one, and the classic version of that mistake is
        running a migration against production because `alembic.ini` still held a stale URL
        (`code-standards.md` §4).

        **`include_object` hides objects this application does not own.** Two kinds: tables belonging to a
        Postgres extension (asked of `pg_depend`, not hard-coded), and the CHECK constraints generated by
        `wire_enum()` columns. Both would otherwise appear as differences on a schema that is identical, and
        the first would have Alembic write `op.drop_table("spatial_ref_sys")` into the next migration.

        **`compare_type=True`.** Off by default, which means a column widened from `VARCHAR(64)` to
        `VARCHAR(256)` in a model produces an empty migration and a silent truncation later.
"""

import asyncio
from logging.config import fileConfig

import sqlalchemy as sa
from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from app.config import settings
from app.db.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The single source of the DSN. Escaped because ConfigParser treats a bare `%` as interpolation, and a
# percent-encoded character in a Supabase password is common enough to be worth handling rather than
# discovering.
config.set_main_option("sqlalchemy.url", str(settings.database_url).replace("%", "%%"))

target_metadata = Base.metadata

# GeoAlchemy2's prefix for the GiST indexes it creates itself. Ours is `ix_`, set by the naming convention
# in `app/db/models/base.py`.
GEOALCHEMY_INDEX_PREFIX: str = "idx_"

# Filled in from the live database before each comparison - see `_load_extension_owned_tables`. Empty in
# offline mode, where there is no connection and no autogenerate.
_extension_owned_tables: set[str] = set()


def _enum_check_constraint_names() -> frozenset[str]:
    """Names of the CHECK constraints generated by `wire_enum()` columns.

    These are declared through the column's `Enum` type rather than as table-level `CheckConstraint`
    objects, so autogenerate reflects them from the database but finds no counterpart in the metadata and
    reports all fifteen as "removed" on a schema that is in fact identical. Excluding them by name is what
    lets `alembic check` mean something: a check that always reports the same fifteen differences is a check
    nobody reads.

    Computed from the metadata rather than listed, so it follows a renamed enum instead of going stale.
    """
    names: set[str] = set()
    for table in target_metadata.tables.values():
        for column in table.columns:
            enum_name = getattr(column.type, "name", None)
            if isinstance(column.type, sa.Enum) and enum_name:
                names.add(f"ck_{table.name}_{enum_name}")
    return frozenset(names)


ENUM_CHECK_CONSTRAINTS: frozenset[str] = _enum_check_constraint_names()


def _load_extension_owned_tables(connection: Connection) -> None:
    """Record every table that belongs to a Postgres extension, so autogenerate leaves them alone.

    Asked of the database rather than hard-coded. PostGIS alone owns `spatial_ref_sys`; with the topology
    and tiger-geocoder extensions installed it owns about a hundred more, and this image puts their schemas
    on the `search_path` so reflection sees them unqualified. Without this filter Alembic writes
    `op.drop_table("spatial_ref_sys")` into the next migration - which deletes every projection the database
    knows and breaks `ST_Transform` everywhere.

    A query rather than a list because we do not control every deployment: `docker/postgis-init/` drops the
    unused extensions locally, but a managed Postgres such as Supabase may install them and we cannot.
    """
    global _extension_owned_tables
    rows = connection.execute(
        sa.text(
            "SELECT c.relname FROM pg_class c "
            "JOIN pg_depend d ON d.objid = c.oid AND d.deptype = 'e' "
            "JOIN pg_extension e ON e.oid = d.refobjid "
            "WHERE c.relkind IN ('r', 'v', 'm', 'f', 'p')"
        )
    ).scalars()
    _extension_owned_tables = set(rows)

    # Close the implicit transaction this read opened, BEFORE Alembic configures the migration context.
    #
    # This is not tidiness. SQLAlchemy 2.0 begins a transaction on first execute; left open, Alembic's own
    # transaction handling nests inside it and never commits the outer one, so every migration runs and is
    # then silently rolled back. It reports "Running downgrade ...", exits 0, and changes nothing - the
    # worst kind of failure, because it looks exactly like success.
    connection.rollback()


def include_object(
    obj: object,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: object,
) -> bool:
    """Exclude objects this application does not own. See the two helpers above."""
    if type_ == "table" and name in _extension_owned_tables:
        return False
    if type_ == "check_constraint" and name in ENUM_CHECK_CONSTRAINTS:
        return False
    # GeoAlchemy2 creates the GiST index for a `spatial_index=True` column itself, through a DDL event on
    # the column. Letting autogenerate also manage it produces a duplicate `CREATE INDEX` on upgrade and a
    # failing `DROP INDEX` on downgrade.
    #
    # `idx_` is GeoAlchemy2's prefix (`idx_scenes_footprint`); ours is `ix_`, set by the naming convention
    # in `app/db/models/base.py`. The two prefixes differing by one character is unfortunate and is exactly
    # why this is checked against a named constant rather than inline.
    if type_ == "index" and name is not None and name.startswith(GEOALCHEMY_INDEX_PREFIX):
        return False
    return True


def _configure(connection: Connection | None = None, url: str | None = None) -> None:
    """Apply the options that must be identical in offline and online mode.

    Shared rather than written twice: the two modes drifting apart is how a migration that passes in CI
    behaves differently when someone generates SQL for a review.
    """
    context.configure(
        connection=connection,
        url=url,
        target_metadata=target_metadata,
        include_object=include_object,
        compare_type=True,
        compare_server_default=True,
        # Every migration runs inside one transaction, so a failure halfway leaves no partly-migrated
        # schema. Postgres supports transactional DDL; this is the reason to use it.
        transaction_per_migration=True,
        render_as_batch=False,
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting. Used to review a migration before it touches anything."""
    _configure(url=config.get_main_option("sqlalchemy.url"))
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    _load_extension_owned_tables(connection)
    _configure(connection=connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Connect with asyncpg and run the migrations.

    `NullPool` because this process runs one migration and exits; a pool would hold connections open past
    the work and, against Supabase, count against the project's connection limit for no benefit.
    """
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
