from enum import StrEnum

class FailureCode(StrEnum):
    MODEL_DOMAIN_MISMATCH = "MODEL_DOMAIN_MISMATCH"
    RESOLUTION_FAILURE = "RESOLUTION_FAILURE"
    MISSING_INPUT = "MISSING_INPUT"
    MODALITY_MISMATCH = "MODALITY_MISMATCH"
    TEMPORAL_MISMATCH = "TEMPORAL_MISMATCH"
    CRS_MISMATCH = "CRS_MISMATCH"
    PARAMETER_INVALID = "PARAMETER_INVALID"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    SCIENTIFIC_INVALID = "SCIENTIFIC_INVALID"
    UNSUPPORTED_INTENT = "UNSUPPORTED_INTENT"
    SYSTEM_ERROR = "SYSTEM_ERROR"
