"""Initial schema: PostGIS, and the seven tables an evidence-grounded run is recorded in.

Revision ID: 0001_initial_schema
Revises:
Created: 2026-08-30

Hand-written rather than autogenerated, for two reasons worth keeping.

`CREATE EXTENSION postgis` must run before any geometry column exists, and autogenerate has no way to know
that - it compares tables, and the extension is a precondition of the comparison rather than a result of it.

Geometry columns are declared with `spatial_index=False` here even though the models declare `True`. That
flag is a DDL-generation hint, not a property of the column, and leaving it on would have GeoAlchemy2 create
the GiST index through its own DDL event *and* have this migration create it explicitly - a duplicate on
upgrade and a failure on downgrade. Declaring the index once, explicitly, is what makes the downgrade
reversible. `migrations/env.py` excludes the same indexes from future autogenerates for the same reason.

The column definitions were verified against DDL compiled directly from `Base.metadata`, not transcribed by
eye.
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Storage CRS for every geometry column. Duplicated from `app.constants.geo.STORAGE_SRID` on purpose: a
# migration is a historical record and must keep applying identically even if the application's constants
# change, so it may not import them.
SRID: int = 4326

_MODEL_IDS = (
    "rs-vlm",
    "grounding-dino-sam",
    "changeformer",
    "sar-change",
    "segformer-landcover",
    "dota-detector",
    "index-engine",
    "geospatial-engine",
    "optical-sar-fusion",
    "s2cloudless",
    "co-registration",
    "sar-preprocess",
)
_STAGE_CODES = tuple(f"S{number}" for number in range(1, 21))


def _enum(*values: str, name: str) -> sa.Enum:
    """A VARCHAR-with-CHECK column, matching `app.db.models.base.wire_enum`'s output byte for byte.

    `name` is mandatory and is the lower-cased Python enum class name, because that is what SQLAlchemy uses
    for `%(constraint_name)s` when the models emit the same column. Get it wrong and the constraint is named
    differently here than in `Base.metadata`, which makes the very next `alembic revision --autogenerate`
    propose dropping and recreating every one of them.
    """
    return sa.Enum(*values, name=name, native_enum=False, length=64, create_constraint=True)


def upgrade() -> None:
    """Create the extension, then the eight tables.

    Every `CheckConstraint` below is given its BARE name. The naming convention in `app/db/models/base.py`
    is `ck_%(table_name)s_%(constraint_name)s` and prefixes it, so passing a full name here produces
    `ck_claims_ck_claims_...` and diverges from what the models describe.
    """
    # Must precede every geometry column. `IF NOT EXISTS` because Supabase provisions PostGIS on some
    # plans, and a migration that fails on a database that is already correct is a migration nobody trusts.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "scenes",
        sa.Column("id", sa.String(32), nullable=False),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modality", _enum("optical", "sar", "multispectral", "hyperspectral", name="scenemodality"), nullable=False),
        sa.Column("sensor_platform", sa.String(128), nullable=False),
        sa.Column("band_count", sa.Integer(), nullable=False),
        sa.Column("ground_sample_distance_meters", sa.Float(), nullable=False),
        sa.Column("cloud_cover_percentage", sa.Float(), nullable=True),
        sa.Column("coordinate_reference_system", sa.String(64), nullable=False),
        sa.Column(
            "footprint",
            geoalchemy2.Geometry(geometry_type="POLYGON", srid=SRID, spatial_index=False),
            nullable=False,
        ),
        sa.Column(
            "centroid",
            geoalchemy2.Geometry(geometry_type="POINT", srid=SRID, spatial_index=False),
            nullable=False,
        ),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("processing_state", _enum("queued", "processing", "ready", "failed", name="sceneprocessingstate"), nullable=False),
        sa.Column("temporal_role", _enum("single", "t0", "t1", name="temporalrole"), nullable=False),
        sa.Column("thumbnail_url", sa.String(1024), nullable=True),
        sa.Column("raw_object_key", sa.String(512), nullable=True),
        sa.Column("cog_object_key", sa.String(512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_scenes"),
        # SAR carries no cloud cover, and NULL is not the same statement as 0 (api-contract.md §1 rule 3).
        sa.CheckConstraint(
            "(modality = 'sar' AND cloud_cover_percentage IS NULL)"
            " OR (modality <> 'sar' AND (cloud_cover_percentage IS NULL"
            " OR cloud_cover_percentage BETWEEN 0 AND 100))",
            name="sar_has_no_cloud_cover",
        ),
        # A scene may only be `ready` once its COG exists. Nothing analyses a scene that is not ready.
        sa.CheckConstraint(
            "processing_state <> 'ready' OR cog_object_key IS NOT NULL",
            name="ready_scene_has_a_cog",
        ),
        sa.CheckConstraint(
            "ground_sample_distance_meters > 0",
            name="ground_sample_distance_is_positive",
        ),
        sa.CheckConstraint("band_count > 0", name="band_count_is_positive"),
    )
    op.create_index("ix_scenes_captured_at_modality", "scenes", ["captured_at", "modality"])
    op.create_index("ix_scenes_processing_state", "scenes", ["processing_state"])
    op.create_index("idx_scenes_footprint", "scenes", ["footprint"], postgresql_using="gist")
    op.create_index("idx_scenes_centroid", "scenes", ["centroid"], postgresql_using="gist")

    op.create_table(
        "missions",
        sa.Column("id", sa.String(32), nullable=False),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("status", _enum("active", "monitoring", "alert", "archived", name="missionstatus"), nullable=False),
        sa.Column("status_rank", sa.Integer(), nullable=False),
        sa.Column(
            "area_of_interest",
            geoalchemy2.Geometry(geometry_type="POLYGON", srid=SRID, spatial_index=False),
            nullable=False,
        ),
        sa.Column(
            "centroid",
            geoalchemy2.Geometry(geometry_type="POINT", srid=SRID, spatial_index=False),
            nullable=False,
        ),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("investigation_id", sa.String(32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_missions"),
    )
    op.create_index("ix_missions_status_rank_updated_at", "missions", ["status_rank", sa.text("updated_at DESC")])
    op.create_index("idx_missions_area_of_interest", "missions", ["area_of_interest"], postgresql_using="gist")
    op.create_index("idx_missions_centroid", "missions", ["centroid"], postgresql_using="gist")

    op.create_table(
        "investigations",
        sa.Column("id", sa.String(32), nullable=False),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("area_of_interest_name", sa.String(256), nullable=False),
        sa.Column(
            "area_of_interest",
            geoalchemy2.Geometry(geometry_type="POLYGON", srid=SRID, spatial_index=False),
            nullable=False,
        ),
        sa.Column(
            "centroid",
            geoalchemy2.Geometry(geometry_type="POINT", srid=SRID, spatial_index=False),
            nullable=False,
        ),
        sa.Column("status", _enum("draft", "running", "ready", "failed", name="investigationstatus"), nullable=False),
        sa.Column("mode", _enum("temporal", "crossModal", name="workspacemode"), nullable=False),
        sa.Column("seed_query", sa.String(2048), nullable=True),
        sa.Column("mission_id", sa.String(32), nullable=True),
        sa.Column("trace_id", sa.String(64), nullable=False),
        sa.Column("camera_bookmark", sa.dialects.postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_investigations"),
        sa.UniqueConstraint("trace_id", name="uq_investigations_trace_id"),
    )
    op.create_index("ix_investigations_status", "investigations", ["status"])
    op.create_index("ix_investigations_updated_at", "investigations", [sa.text("updated_at DESC")])
    op.create_index("idx_investigations_area_of_interest", "investigations", ["area_of_interest"], postgresql_using="gist")
    op.create_index("idx_investigations_centroid", "investigations", ["centroid"], postgresql_using="gist")

    # The two foreign keys between investigations and missions are a genuine cycle - an investigation names
    # the mission it belongs to, a mission names the investigation it was promoted from. Both tables must
    # exist before either constraint can be added, so both are added here.
    op.create_foreign_key(
        "fk_missions_investigation_id_investigations",
        "missions",
        "investigations",
        ["investigation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_investigations_mission_id_missions",
        "investigations",
        "missions",
        ["mission_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_table(
        "investigation_scenes",
        sa.Column("investigation_id", sa.String(32), nullable=False),
        sa.Column("scene_id", sa.String(32), nullable=False),
        sa.Column("role", _enum("t0", "t1", "sar", "aux", name="scenerole"), nullable=False),
        sa.PrimaryKeyConstraint("investigation_id", "scene_id", "role", name="pk_investigation_scenes"),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name="fk_investigation_scenes_investigation_id_investigations",
            ondelete="CASCADE",
        ),
        # RESTRICT: deleting a scene an investigation was built on would silently change what its completed
        # runs were computed from, which breaks provenance.
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
            name="fk_investigation_scenes_scene_id_scenes",
            ondelete="RESTRICT",
        ),
    )
    # One scene per singular role. `aux` is excluded, since an investigation may hold several reference
    # scenes; two scenes both claiming to be `t1` would make the comparator render by row order.
    op.create_index(
        "uq_investigation_scenes_singular_role",
        "investigation_scenes",
        ["investigation_id", "role"],
        unique=True,
        postgresql_where=sa.text("role <> 'aux'"),
    )
    op.create_index("ix_investigation_scenes_scene_id", "investigation_scenes", ["scene_id"])

    op.create_table(
        "runs",
        sa.Column("id", sa.String(32), nullable=False),
        sa.Column("investigation_id", sa.String(32), nullable=False),
        sa.Column("query", sa.String(2048), nullable=False),
        sa.Column(
            "intent",
            _enum(
                "SCENE_VQA",
                "GROUND",
                "INDEX_QUERY",
                "DETECT",
                "SEGMENT",
                "CHANGE_DETECT",
                "CHANGE_VQA",
                "CROSS_MODAL",
                "EVIDENCE_RECALL",
                name="intent",
            ),
            nullable=True,
        ),
        sa.Column("status", _enum("running", "complete", "failed", "cancelled", name="runstatus"), nullable=False),
        sa.Column(
            "region_bounds",
            geoalchemy2.Geometry(geometry_type="POLYGON", srid=SRID, spatial_index=False),
            nullable=True,
        ),
        sa.Column("plan_id", sa.String(32), nullable=True),
        sa.Column("operation_id", sa.String(128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_duration_ms", sa.Integer(), nullable=True),
        # NULL means "declined to assert". Never defaulted to 0.0 (api-contract.md §1 rule 2).
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("insufficient_evidence", sa.dialects.postgresql.JSONB(), nullable=True),
        sa.Column("error_message", sa.String(1024), nullable=True),
        sa.Column("checkpoint_thread_id", sa.String(128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_runs"),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name="fk_runs_investigation_id_investigations",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("checkpoint_thread_id", name="uq_runs_checkpoint_thread_id"),
    )
    op.create_index("ix_runs_investigation_id_started_at", "runs", ["investigation_id", sa.text("started_at DESC")])

    op.create_table(
        "trace_steps",
        sa.Column("id", sa.String(32), nullable=False),
        sa.Column("run_id", sa.String(32), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("stage_code", _enum(*_STAGE_CODES, name="pipelinestage"), nullable=False),
        sa.Column("state", _enum("pending", "running", "completed", "failed", "skipped", name="tracestepstate"), nullable=False),
        sa.Column("detail", sa.String(512), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("model_id", _enum(*_MODEL_IDS, name="modelid"), nullable=True),
        sa.Column("model_version", sa.String(64), nullable=True),
        sa.Column("artefact_object_key", sa.String(512), nullable=True),
        sa.Column("artefact_layer_id", sa.String(32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_trace_steps"),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name="fk_trace_steps_run_id_runs", ondelete="CASCADE"
        ),
        sa.UniqueConstraint("run_id", "sequence", name="one_step_per_position"),
    )
    op.create_index("ix_trace_steps_run_id_sequence", "trace_steps", ["run_id", "sequence"])

    op.create_table(
        "evidence",
        sa.Column("id", sa.String(32), nullable=False),
        sa.Column("run_id", sa.String(32), nullable=False),
        sa.Column(
            "kind",
            _enum("change-mask", "detection", "index-map", "scene-crop", "statistic", "cross-modal", name="evidencekind"),
            nullable=False,
        ),
        sa.Column("title", sa.String(256), nullable=False),
        sa.Column("layer_id", sa.String(32), nullable=True),
        sa.Column("feature_ids", sa.dialects.postgresql.JSONB(), nullable=False),
        # MULTIPOLYGON: a change mask over one area is genuinely several disjoint patches.
        sa.Column(
            "geometry",
            geoalchemy2.Geometry(geometry_type="MULTIPOLYGON", srid=SRID, spatial_index=False),
            nullable=True,
        ),
        sa.Column("area_hectares", sa.Float(), nullable=True),
        sa.Column("magnitude", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source_scene_ids", sa.dialects.postgresql.JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_evidence"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name="fk_evidence_run_id_runs", ondelete="CASCADE"),
        # Every evidence kind except a scalar statistic is a place. Evidence with no geometry is the
        # unauditable output this architecture exists to prevent.
        sa.CheckConstraint(
            "kind = 'statistic' OR geometry IS NOT NULL",
            name="spatial_evidence_has_geometry",
        ),
        sa.CheckConstraint("magnitude BETWEEN 0 AND 1", name="magnitude_is_a_fraction"),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name="confidence_is_a_fraction_or_null",
        ),
        sa.CheckConstraint(
            "area_hectares IS NULL OR area_hectares >= 0",
            name="area_is_not_negative",
        ),
    )
    op.create_index("ix_evidence_run_id", "evidence", ["run_id"])
    op.create_index("idx_evidence_geometry", "evidence", ["geometry"], postgresql_using="gist")

    op.create_table(
        "claims",
        sa.Column("id", sa.String(32), nullable=False),
        sa.Column("run_id", sa.String(32), nullable=False),
        sa.Column("text", sa.String(2048), nullable=False),
        sa.Column("kind", _enum("quantitative", "spatial", "categorical", "negative", name="claimkind"), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("metrics", sa.dialects.postgresql.JSONB(), nullable=False),
        sa.Column("evidence_ids", sa.dialects.postgresql.JSONB(), nullable=False),
        sa.Column("model_id", _enum(*_MODEL_IDS, name="modelid"), nullable=False),
        sa.Column("model_version", sa.String(64), nullable=False),
        sa.Column("trace_step_id", sa.String(32), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_claims"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name="fk_claims_run_id_runs", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["trace_step_id"],
            ["trace_steps.id"],
            name="fk_claims_trace_step_id_trace_steps",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name="confidence_is_a_fraction_or_null",
        ),
    )
    op.create_index("ix_claims_run_id", "claims", ["run_id"])
    # Exactly one headline claim per run. A run with two headlines has no headline.
    op.create_index(
        "uq_claims_one_primary_per_run",
        "claims",
        ["run_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )


def downgrade() -> None:
    # Reverse creation order. The two cyclic foreign keys are dropped first so neither table blocks the
    # other's removal.
    op.drop_constraint("fk_investigations_mission_id_missions", "investigations", type_="foreignkey")
    op.drop_constraint("fk_missions_investigation_id_investigations", "missions", type_="foreignkey")

    op.drop_table("claims")
    op.drop_table("evidence")
    op.drop_table("trace_steps")
    op.drop_table("runs")
    op.drop_table("investigation_scenes")
    op.drop_table("investigations")
    op.drop_table("missions")
    op.drop_table("scenes")

    # The extension is deliberately NOT dropped. It may predate this schema - Supabase provisions it on some
    # plans - and another schema in the same database may hold geometry columns. Dropping a shared extension
    # to undo one application's migration is not a reversal, it is collateral damage.
