"""add_project_columns

Revision ID: 433e6cdd898c
Revises: c4532e60526b
Created: 2026-09-20 04:13:39.491966+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '433e6cdd898c'
down_revision: str | None = 'c4532e60526b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    import geoalchemy2
    op.add_column('projects', sa.Column('area_of_interest_name', sa.String(length=256), server_default='', nullable=False))
    op.add_column('projects', sa.Column('area_of_interest', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('projects', sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('projects', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'last_activity_at')
    op.drop_column('projects', 'centroid')
    op.drop_column('projects', 'area_of_interest')
    op.drop_column('projects', 'area_of_interest_name')
    # ### end Alembic commands ###
