"""Phase 2 database foundation

Revision ID: e757afab871d
Revises: 0001_initial_schema
Created: 2026-09-17 13:44:57.261970+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'e757afab871d'
down_revision: str | None = '0001_initial_schema'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('investigation_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('command_id', sa.String(length=256), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_history_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_history'))
    )
    op.create_index('ix_investigation_history_investigation_id_at', 'investigation_history', ['investigation_id', sa.literal_column('at ASC')], unique=False)
    op.create_table('investigation_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_versions_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_versions'))
    )
    op.create_index('ix_investigation_versions_investigation_id_created_at', 'investigation_versions', ['investigation_id', sa.literal_column('created_at DESC')], unique=False)
    op.add_column('investigations', sa.Column('project_id', sa.String(length=32), nullable=True))
    op.add_column('investigations', sa.Column('template_version_id', sa.String(length=256), nullable=True))
    op.create_foreign_key(op.f('fk_investigations_project_id_projects'), 'investigations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('missions', sa.Column('project_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(op.f('fk_missions_project_id_projects'), 'missions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_missions_project_id_projects'), 'missions', type_='foreignkey')
    op.drop_column('missions', 'project_id')
    op.drop_constraint(op.f('fk_investigations_project_id_projects'), 'investigations', type_='foreignkey')
    op.drop_column('investigations', 'template_version_id')
    op.drop_column('investigations', 'project_id')
    op.drop_index('ix_investigation_versions_investigation_id_created_at', table_name='investigation_versions')
    op.drop_table('investigation_versions')
    op.drop_index('ix_investigation_history_investigation_id_at', table_name='investigation_history')
    op.drop_table('investigation_history')
    op.drop_table('projects')
    # ### end Alembic commands ###
